- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  
  tasks: 
     - name: create new deployment
       command: kubectl apply -f /home/ubuntu/Deployment.yml
     - name: create new service
       command: kubectl apply -f /home/ubuntu/Service.yml
